name: wiki

x-setup-base: &x-setup-base
  image: ghcr.io/changpopwiki/wiki-setup:latest
  volumes:
    - non_bundled_extensions:/non-bundled
    - extensions_loader:/extensions-loader
    - ./config/mediawiki:/config

services:
  mediawiki:
    image: ghcr.io/changpopwiki/wiki-mediawiki:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail",
              "http://localhost/api.php?action=query&meta=siteinfo&format=json" ]
      interval: 30s
      start_period: 10s
      start_interval: 1s
      retries: 3
    depends_on:
      database:
        condition: service_started
      setup:
        condition: service_completed_successfully
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data/images:/var/www/html/images
      - ./config/mediawiki:/var/www/html/config:ro
      - ./mounted/mediawiki/logo.svg:/var/www/html/resources/assets/logo.svg:ro
      - ./config/caddy:/etc/caddy:ro
      - non_bundled_extensions:/non-bundled
      - extensions_loader:/var/www/html/extensions-loader:ro
    networks:
      chp_proxy:
      default:

  setup:
    <<: *x-setup-base

  setup-force:
    <<: *x-setup-base
    restart: no
    profiles:
      - setup-force
    command:
      - "--force"

  database:
    image: mariadb:lts-ubi
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      CARGOUSER_PASSWORD: ${CARGOUSER_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mounted/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  backup:
    image: ghcr.io/changpopwiki/wiki-backup:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_started
      mediawiki:
        condition: service_started
    environment:
      # DB 연결 정보
      - MARIADB_HOST=database
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

      # 매일 06시에 백업 실행
      - CRON_TIME=0 6 * * *

      # 일간 백업 보존 개수
      - MAX_DAILY_BACKUPS=${MAX_DAILY_BACKUPS}

      # rclone 환경 변수
      - RCLONE_CONFIG_B2_TYPE=b2
      - RCLONE_CONFIG_B2_ACCOUNT=${B2_KEY_ID}
      - RCLONE_CONFIG_B2_KEY=${B2_KEY}
      - RCLONE_REMOTE=B2:${B2_BUCKET_NAME}${B2_BUCKET_PATH}

      # 페이지 백업용 환경변수
      - GITHUB_APP_ID=${BACKUP_PAGES_GITHUB_APP_ID}
      - GITHUB_INSTALLATION_ID=${BACKUP_PAGES_GITHUB_INSTALLATION_ID}
      - GITHUB_REPO=${BACKUP_PAGES_GITHUB_REPO}
      - GITHUB_SECRET_KEY_PATH=/run/secrets/backup-pages-github-app-pem
    volumes:
      - ./data/db_dump:/backup
    secrets:
      - backup-pages-github-app-pem

volumes:
  db_data:
  non_bundled_extensions:
  extensions_loader:

networks:
  chp_proxy:
    external: true

secrets:
  backup-pages-github-app-pem:
    file: ./secrets/backup-pages-github-app.pem
