services:
  mediawiki:
    build:
      context: build-context/mediawiki
    env_file: []   # 빌드 시 env_file 무시
    ports:
      # 기본 포트: 10597, .env 파일에서 DEV_SERVICE_PORT을 설정하여 변경 가능
      - "${DEV_SERVICE_PORT:-10597}:80"
    volumes:
      - ./dev/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
  setup:
    build:
      context: build-context/setup
  backup:
    build:
      context: build-context/backup